-- Step 1: Check if permit exists in FILTERED_PERMITS
SELECT '1-FILTERED_PERMITS' AS Step, * 
FROM B1PERMIT
WHERE B1_ALT_ID = '2021-MSS-RES-01014'
AND B1_PER_GROUP = 'Building'
AND B1_PER_TYPE IN ('Residential Construction', 'Commercial Construction')
AND B1_APPL_CLASS = 'COMPLETE'
AND B1_APPL_STATUS NOT IN ('Closed', 'Withdrawn', 'Refunded');

-- Step 2: Check if the permit's ID exists in PERMIT_TYPE
SELECT '2-PERMIT_TYPE' AS Step, BCHCKBOX.* 
FROM BCHCKBOX
JOIN B1PERMIT ON BCHCKBOX.B1_PER_ID1 = B1PERMIT.B1_PER_ID1
    AND BCHCKBOX.B1_PER_ID2 = B1PERMIT.B1_PER_ID2
    AND BCHCKBOX.B1_PER_ID3 = B1PERMIT.B1_PER_ID3
WHERE B1PERMIT.B1_ALT_ID = '2021-MSS-RES-01014'
AND BCHCKBOX.B1_CHECKBOX_DESC IN ('Commercial Subtype', 'Residential Subtype');

-- Step 3: Check if the permit's ID exists in PROJECT_TYPE
SELECT '3-PROJECT_TYPE' AS Step, BCHCKBOX.* 
FROM BCHCKBOX
JOIN B1PERMIT ON BCHCKBOX.B1_PER_ID1 = B1PERMIT.B1_PER_ID1
    AND BCHCKBOX.B1_PER_ID2 = B1PERMIT.B1_PER_ID2
    AND BCHCKBOX.B1_PER_ID3 = B1PERMIT.B1_PER_ID3
WHERE B1PERMIT.B1_ALT_ID = '2021-MSS-RES-01014'
AND BCHCKBOX.B1_CHECKBOX_DESC = 'New Construction';

-- Step 4: Check ID values to make sure they match between tables
SELECT
    'ID-COMPARISON' AS Step,
    fp.B1_PER_ID1 AS Filtered_ID1,
    fp.B1_PER_ID2 AS Filtered_ID2,
    fp.B1_PER_ID3 AS Filtered_ID3,
    pt.B1_PER_ID1 AS PermitType_ID1,
    pt.B1_PER_ID2 AS PermitType_ID2,
    pt.B1_PER_ID3 AS PermitType_ID3,
    pjt.B1_PER_ID1 AS ProjectType_ID1,
    pjt.B1_PER_ID2 AS ProjectType_ID2,
    pjt.B1_PER_ID3 AS ProjectType_ID3
FROM
    (SELECT B1_PER_ID1, B1_PER_ID2, B1_PER_ID3 FROM B1PERMIT WHERE B1_ALT_ID = '2021-MSS-RES-01014') fp
LEFT JOIN
    (SELECT DISTINCT B1_PER_ID1, B1_PER_ID2, B1_PER_ID3 FROM BCHCKBOX WHERE B1_CHECKBOX_DESC IN ('Commercial Subtype', 'Residential Subtype')) pt
    ON fp.B1_PER_ID1 = pt.B1_PER_ID1 AND fp.B1_PER_ID2 = pt.B1_PER_ID2 AND fp.B1_PER_ID3 = pt.B1_PER_ID3
LEFT JOIN
    (SELECT DISTINCT B1_PER_ID1, B1_PER_ID2, B1_PER_ID3 FROM BCHCKBOX WHERE B1_CHECKBOX_DESC = 'New Construction') pjt
    ON fp.B1_PER_ID1 = pjt.B1_PER_ID1 AND fp.B1_PER_ID2 = pjt.B1_PER_ID2 AND fp.B1_PER_ID3 = pjt.B1_PER_ID3;

-- Step 5: Check the full PERMIT_DETAILS construction
SELECT 
    'PERMIT_DETAILS' AS Step,
    FILTERED_PERMITS.B1_ALT_ID,
    FILTERED_PERMITS.B1_PER_TYPE,
    PERMIT_TYPE.PERMIT_TYPE_x,
    PROJECT_TYPE.Project_Type
FROM 
    (SELECT 
        B1_PER_ID1, B1_PER_ID2, B1_PER_ID3, B1_ALT_ID,
        CASE 
            WHEN B1_PER_TYPE = 'Residential Construction' THEN 'Residential'
            WHEN B1_PER_TYPE = 'Commercial Construction' THEN 'Commercial'
            ELSE 'Unknown'
        END AS B1_PER_TYPE
     FROM B1PERMIT
     WHERE B1_ALT_ID = '2021-MSS-RES-01014'
     AND B1_PER_GROUP = 'Building'
     AND B1_PER_TYPE IN ('Residential Construction', 'Commercial Construction')
    ) FILTERED_PERMITS
LEFT JOIN 
    (SELECT
        B1_PER_ID1, B1_PER_ID2, B1_PER_ID3,
        MIN(B1_CHECKLIST_COMMENT) AS PERMIT_TYPE_x
     FROM BCHCKBOX
     WHERE B1_CHECKBOX_DESC IN ('Commercial Subtype', 'Residential Subtype')
     GROUP BY B1_PER_ID1, B1_PER_ID2, B1_PER_ID3
    ) PERMIT_TYPE
    ON FILTERED_PERMITS.B1_PER_ID1 = PERMIT_TYPE.B1_PER_ID1
    AND FILTERED_PERMITS.B1_PER_ID2 = PERMIT_TYPE.B1_PER_ID2
    AND FILTERED_PERMITS.B1_PER_ID3 = PERMIT_TYPE.B1_PER_ID3
LEFT JOIN 
    (SELECT
        B1_PER_ID1, B1_PER_ID2, B1_PER_ID3,
        CASE
            WHEN B1_CHECKLIST_COMMENT = 'CHECKED' THEN 'New Construction'
            ELSE 'Addition/Remodel'
        END AS Project_Type
     FROM BCHCKBOX
     WHERE B1_CHECKBOX_DESC = 'New Construction'
    ) PROJECT_TYPE
    ON FILTERED_PERMITS.B1_PER_ID1 = PROJECT_TYPE.B1_PER_ID1
    AND FILTERED_PERMITS.B1_PER_ID2 = PROJECT_TYPE.B1_PER_ID2
    AND FILTERED_PERMITS.B1_PER_ID3 = PROJECT_TYPE.B1_PER_ID3; 